/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#92002a",
                "on-surface": "#0b1c30",
                "tertiary-fixed-dim": "#ffb2b7",
                "primary-fixed": "#6ffbbe",
                "on-primary-fixed-variant": "#005236",
                "tertiary": "#bc0b3b",
                "on-primary-fixed": "#002113",
                "inverse-on-surface": "#eaf1ff",
                "on-tertiary-container": "#780021",
                "error-container": "#ffdad6",
                "secondary": "#4648d4",
                "on-primary": "#ffffff",
                "on-error": "#ffffff",
                "surface-container-highest": "#d3e4fe",
                "outline-variant": "#bbcabf",
                "inverse-surface": "#213145",
                "on-error-container": "#93000a",
                "on-surface-variant": "#3c4a42",
                "error": "#ba1a1a",
                "surface-bright": "#f8f9ff",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#4edea3",
                "tertiary-container": "#ff7886",
                "secondary-fixed": "#e1e0ff",
                "tertiary-fixed": "#ffdadb",
                "surface-container-lowest": "#ffffff",
                "background": "#f8f9ff",
                "secondary-container": "#6063ee",
                "surface": "#f8f9ff",
                "surface-container": "#e5eeff",
                "on-background": "#0b1c30",
                "primary-container": "#10b981",
                "surface-dim": "#cbdbf5",
                "secondary-fixed-dim": "#c0c1ff",
                "on-secondary-fixed-variant": "#2f2ebe",
                "on-secondary-fixed": "#07006c",
                "on-tertiary-fixed": "#40000d",
                "surface-variant": "#d3e4fe",
                "surface-container-high": "#dce9ff",
                "on-secondary-container": "#fffbff",
                "on-primary-container": "#00422b",
                "surface-tint": "#006c49",
                "surface-container-low": "#eff4ff",
                "outline": "#6c7a71",
                "primary": "#006c49",
                "on-tertiary": "#ffffff",
                "inverse-primary": "#4edea3"
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                "stack-sm": "0.5rem",
                "sidebar-width": "260px",
                "card-padding": "1.5rem",
                "gutter": "1.5rem",
                "stack-md": "1rem",
                "container-margin": "2rem"
            },
            fontSize: {
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
                "label-xs": ["12px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
                "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }]
            }
        },
    },
    plugins: [],
}