server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript

spring:
  profiles:
    active: local
  jpa:
    open-in-view: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
