server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tsm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:29102006}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
